"""The pinned integrity of the Node.js core the bridge loads.

GENERATED by ``scripts/core-integrity.py write``; do not edit.

``tree`` is the "rsv-tree-v1" digest of the package's directory as npm installs it: SHA-256 over one line per regular
file, ``<sha256 of the content> <size> <relative path>`` sorted by the UTF-8 bytes of the path. ``tarball`` is the npm
``integrity`` value of the published tarball (``package-lock.json``), kept so that a reviewer can see the pin and the
lock agree. ``scripts/core-integrity.py check`` recomputes every ``tree`` from the published tarballs in CI.
"""

from __future__ import annotations

ALGORITHM = "rsv-tree-v1"

CORE_PACKAGES = {
    "@redact-secret/core": {
        "version": "0.1.0-beta.14",
        "tarball": "sha512-1h5NxUto2ZEqQD5hfIgbzwDZkmu6WXdlmtF0waG3FcKDhpCEoUphgj4B4VGRyhVhjJOFT58/TrER+3EL1bCnag==",
        "tree": "84ff945724983cdad95609a4062ebbdbac760f881a082a90274e391f3842371f",
    },
    "@redact-secret/wasm": {
        "version": "0.1.0-beta.14",
        "tarball": "sha512-GbNKLcvEWVzojswaInd+sZgLRkYolAU6IeKNCYvUIIQWaPcrPuLcHitixBTqeS0IEHxWbFkI6RyfMBZyVTPrBQ==",
        "tree": "81ec9fc7064cc3c65be0efb50cce9bb85c1c1915f29dbf4d09c7f90824431a41",
    },
    "@redact-secret/node-darwin-arm64": {
        "version": "0.1.0-beta.14",
        "tarball": "sha512-ARFG6EaEZwHGOCnaPqqtlF5BljxQ6sNAA74N7QU159EvVYCEZvg8gzSeDgt0kjJdJL+vlEjT1zWov+MoZV8KMA==",
        "tree": "9575d8e464f55dd3ae20f0ea284daec5ec0ac2a5ef499d873eb4fdb059c07754",
    },
    "@redact-secret/node-darwin-x64": {
        "version": "0.1.0-beta.14",
        "tarball": "sha512-xAiObLUcaFjPXJ07NRt/LcfjNUKUYCwEpf9lE2v3PfXY7xnkSBop9h06rLjEziR4XjPilb2pQeuuiO3PbzBNKA==",
        "tree": "81199c54f8a0e2178bb9eb591a66c3b2dbfb250ac2dbd4bef517d3c4a0ad834c",
    },
    "@redact-secret/node-linux-arm64-gnu": {
        "version": "0.1.0-beta.14",
        "tarball": "sha512-v1yP2VwFyP0o9qV32jECFId9jTvRjGTFyDpwn3wMCix+9iST7fSDhakEaEKJMifBCx/tfMy/1mXltF/pKPYdDA==",
        "tree": "04d221fd25ad2b790eb43e860395c02991c86c040b08a20d802f9655a482d4ec",
    },
    "@redact-secret/node-linux-arm64-musl": {
        "version": "0.1.0-beta.14",
        "tarball": "sha512-R8Fp1QHyVIOH+qGKcfLZbmEP4gG3sLpIKkmuzfx1sjN23WEvUz3O4UYL9DXJpXYZPG4QWPZuxSewpmGYuw6f2A==",
        "tree": "356d23af356b761c3ec21e820fffff4235ef4d243a14de765b2aaff32400b7c2",
    },
    "@redact-secret/node-linux-x64-gnu": {
        "version": "0.1.0-beta.14",
        "tarball": "sha512-LaNrvAeyzMgSlj7rXghK8LBUIDuCR5nDt7exXzyRgJRvP0jz3zeZGS4KSkbyQtrf90cyAs3VAb5ONMt5XVOwtA==",
        "tree": "59ec65921762667848cb427536b49fed35f9046129a2aa025d220087689c9a4d",
    },
    "@redact-secret/node-linux-x64-musl": {
        "version": "0.1.0-beta.14",
        "tarball": "sha512-DOvm796wqFx9aWL49ZCAmEaHymqxVMHbJudnmSxtrPY2kdWeTR4Hy+fTKZ8lODCTsbWfJoeMK6W55F2TcNC4HA==",
        "tree": "d54cbbefafc6d784097e3eebdad3ac285d6631a48b85148890c15a5ec3915c7a",
    },
    "@redact-secret/node-win32-arm64-msvc": {
        "version": "0.1.0-beta.14",
        "tarball": "sha512-OoNSo5+AyT4s2Za9lmKhvp7qcCDOVd/DluuB02n7gmpg2Wf1TfSZCkDwvgK1RWUw92onghrKXKVWgDjMjZL2zw==",
        "tree": "e2db696898de52c54a15bf7c85ee8fe35564eb2bf07b16e9282f455dacfae38d",
    },
    "@redact-secret/node-win32-x64-msvc": {
        "version": "0.1.0-beta.14",
        "tarball": "sha512-L3y7yMRCtkZIfQkx44UdRLbPPGqN8xyO+RCYo903IMeaVmoBV+7wOS6bCghyzvj57D+EKDl4ORJq952dsFvcpA==",
        "tree": "c56fee9500a9636978e63bbe7429e3901c8a9ab8e04b04f258e46be3f023cd6f",
    },
}
